=== nkashy1/tensorio-models/aggregator/schemas/schema.json
{
  "$schema":  "http://json-schema.org/draft-07/schema#",
  "$id":      "https://github.com/doc-ai/tensorio/schemas/v0.9.0/tioresult/schema.json",

  "definitions": {

    "output": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "Mean"
      ],
      "properties": {
        "Mean":    { "type": "number" }
      }
    },

    "taskParameters": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "numEpochs",
        "batchSize",
        "placeholders"
      ],
      "properties": {
        "numEpochs":    { "type": "integer" },
        "batchSize":    { "type": "integer" },
        "placeholders": { "type": "null"}
      }
    },

    "deviceInfo": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "deviceType",
        "osVersion",
        "tensorIOVersion"
      ],
      "properties": {
        "deviceType":    { "type": "string" },
        "osVersion":    { "type": "string" },
        "tensorIOVersion":    { "type": "string" }
      }
    },

    "profiling": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "cpuTime"
      ],
      "properties": {
        "cpuTime":    { "type": "number" }
      }
    }

  },

  "type": "object",
  "additionalProperties": false,
  "required": [
    "taskId",
    "numSamples",
    "taskParameters",
    "deviceInfo"
  ],
  "properties": {
    "taskId":             { "type": "string" },
    "clientId":           { "type": "string" },
    "numSamples":          { "type": "integer" },
    "output":  { "$ref": "#/definitions/output" },
    "taskParameters":  { "$ref": "#/definitions/taskParameters" },
    "deviceInfo":            { "$ref": "#/definitions/deviceInfo" },
    "profiling":            { "$ref": "#/definitions/profiling" }
  }
}

=== nkashy1/tensorio-models/aggregator/schemas/tests/valid/basic-result.json
{
  "taskId": "task-123",
  "clientId": "UUID2",
  "numSamples": 123,
  "output": {
    "Mean": 0.01445
  },
  "taskParameters": {
    "batchSize": 10,
    "numEpochs": 5,
    "placeholders" : null
  },
  "deviceInfo": {
    "deviceType": "iPhone X",
    "osVersion": "iOS 12.1",
    "tensorIOVersion": "0.8.1"
  },
  "profiling": {
    "cpuTime": 1200.50
  }
}
